export default {  
    username: 'suman@founderandlightning.com',
    password: 'Suman12345!',
    messageTeamTab: 'A quick overview of your team. Here you can edit member information, change instant categories and add/remove users.',
    messageInAddMemberForm: 'Adding a new team member will increase the subscription price by £5+VAT per month.',
    passwordForMember: 'Test123456!',
    firstname: 'Tester',
    lastName: 'Malishka',
    errorMsgForRegisteredUser: 'This email has already been taken. Please sign in or choose an alternative email address',
    errorMsg_FN: 'Please enter your first name',
    errorMsg_LN: 'Please enter your last name',
    errorMsg_email: 'Please enter an email address',
    firstNamewithSpecialCharAndNumbers: '1234$%^',
    lastNamewithSpecialCharAndNumbers : '!@#1234',
    invalidEmail: 'suman@#$12344',
    errorMsg_FN_specialChar_numbers: 'Please remove special characters or numbers in first name',
    errorMsg_LN_specialChar_numbers: 'Please remove special characters or numbers in last name',
    errorMsg_email_specialChar_numbers: 'Please enter a valid email address',
    errorMsg_emailNotVerified: 'Your email address is not verified',
    pastDate: '02/02/2023',
    invalidDate: '1234567',
    futureDate: '10/10/2024',
    errorMsgForPastDate: 'Please enter a future date',
    errorMsgForInvalidDate: 'The date is invalid. Please enter in the date format DD/MM/YYYY',


  };