import './globals.css'
import { Inter } from 'next/font/google'
import AuthProvider from "@/common/utils/authProvider";
import React from "react";

const primaryFont = Inter({
  weight: 'variable',
  subsets: ['latin'],
  variable: '--font-primaryFont',
});

export const metadata = {
  title: 'Editorielle',
  description: 'Generated by Editorielle',
}

export default function RootLayout ({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${primaryFont.variable} font-primary`}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
